### ISSUE TITLE
[DataCap Application] my org - my project

### ISSUE THREAD

**Issue by xinaxu** [xinaxu/filecoin-plus-large-datasets#1]
### Organization Name

test org

### Website / Social Media

test website

### Total amount of DataCap being requested

500 TiB

### Weekly allocation of DataCap requested

100 TiB

### On-chain address for first allocation

f1xxxxx

### Share a brief history of your project and organization

```text
My project is brilliant
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
My other brilliant projects
```

### Describe the data being stored onto Filecoin

```text
Those are awesome data I've collected for fun
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### How do you plan to prepare the dataset

singularity

### Please share a sample of the data

```text
I don't have it right now
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### If you chose not to confirm, what was the reason

```text
I don't know, maybe it's not legit?
```

### What is the expected retrieval frequency for this data

Never

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, Africa, North America, South America

### How will you be distributing your data to storage providers

HTTP or FTP server

### How do you plan to choose SP

I don't know yet

### How do you plan to make deals to your storage providers

Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by Irmagogo** [comment]
Hey, This is a good proposal. But there is one thing made me confuse. 
What's the exactly meaning of "If you chose others, what is the tool or platform you plan to use" ? 
What's the meaning of "others" ? The meaning of "others" in this context may create some ambiguity.
It would be better to make it clearly.

**Comment by xinaxu** [comment]
Thanks @IrmaJiang for pointing it out. The "others" refer to the option only visible in the issue template but once the issue is generated it is indeed very confusing. I'll make some changes.

**Comment by xinaxu** [comment]
Updated here #2
